#!/bin/sh

# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# WiMAX Support Note: All WiMAX framework and library proprietary blobs
# needed for this build are available at
# http://code.google.com/android/nexus/drivers.html#crespo4g

VENDOR=samsung
DEVICE=xcover

rm -rf ../../../vendor/$VENDOR/$DEVICE/*
mkdir -p ../../../vendor/$VENDOR/$DEVICE/proprietary

ZIP="true"

#if [ -f "$1" ]; then
#	rm -rf tmp
#	mkdir tmp
#	unzip -q "$1" -d tmp
#	if [ $? != 0 ]; then
#		echo "$1 is not a valid zip file. Bye."
#		exit 1
#	fi
#	ZIP="true"
#	echo "$1 successfully unzip'd. Copying files..."
#else
#	unset ZIP
#fi

DIRS="
bin
cameradata
etc
etc/firmware
etc/firmware/mrvl
lib
lib/hw
media
"

for DIR in $DIRS; do
	mkdir -p ../../../vendor/$VENDOR/$DEVICE/proprietary/$DIR
	chmod 0755 ../../../vendor/$VENDOR/$DEVICE/proprietary/$DIR
done

FILES="
etc/vold.fstab
etc/gps.conf
etc/firmware/mrvl/WlanCalData_ext.conf
etc/firmware/mrvl/w8787_wlan_SDIO_bt_SDIO.bin
etc/firmware/mrvl/sd8787_uapsta.bin
etc/wifidirect_defaults.conf
cameradata/datapattern_420sp.yuv
cameradata/datapattern_front_420sp.yuv
cameradata/datapattern_420sp_alkon.yuv
lib/lib_gsd4t.so
lib/lib_gsd4t_factory.so
lib/libcamera.so
lib/libmarvell-ril.so
lib/libsecutil.so
lib/libriloemhook.so
lib/libsvcmd.so
lib/libMarvellWireless.so
lib/libmrvldut.so
lib/hw/sensors.default.so
lib/hw/gps.default.so
lib/hw/lights.default.so
bin/npsmobex
bin/mrvlhcitool
bin/MarvellWirelessDaemon
bin/mcfg
bin/mfgloader
bin/mwu
bin/mwu_cli
bin/mpdc
bin/mpdc_d
bin/mpdc_svr
bin/memsicd
bin/rfkill
bin/samsung_debug
bin/wifidir_init.conf
bin/uap.conf
bin/wlandutservice
bin/playlpm
bin/charging_mode
bin/passcodemanager
bin/pxidle
bin/pxksymaddr
lib/libQmageDecoder.so
media/battery_charging_5.qmg
media/battery_charging_10.qmg
media/battery_charging_15.qmg
media/battery_charging_20.qmg
media/battery_charging_25.qmg
media/battery_charging_30.qmg
media/battery_charging_35.qmg
media/battery_charging_40.qmg
media/battery_charging_45.qmg
media/battery_charging_50.qmg
media/battery_charging_55.qmg
media/battery_charging_60.qmg
media/battery_charging_65.qmg
media/battery_charging_70.qmg
media/battery_charging_75.qmg
media/battery_charging_80.qmg
media/battery_charging_85.qmg
media/battery_charging_90.qmg
media/battery_charging_95.qmg
media/battery_charging_100.qmg
media/chargingwarning.qmg
media/Disconnected.qmg
"

#etc/mrvl.cfg
#lib/libbmm.so
#lib/libpmemhelper.so
#lib/libphycontmem.so
#lib/libgcu.so
#lib/libGAL.so
#lib/libopencore_author.so
#lib/libopencore_common.so
#lib/libopencore_download.so
#lib/libopencore_downloadreg.so
#lib/libopencore_mp4local.so
#lib/libopencore_mp4localreg.so
#lib/libopencore_net_support.so
#lib/libopencore_player.so
#lib/libopencore_rtsp.so
#lib/libopencore_rtspreg.so
#lib/libopencorehw.so
#lib/egl/libEGL_MRVL.so
#lib/egl/libGLESv1_CM_MRVL.so
#lib/egl/libGLESv2_MRVL.so

for FILE in $FILES; do
	echo $FILE
	if [ "$ZIP" ]; then
		cp system/"$FILE" ../../../vendor/$VENDOR/$DEVICE/proprietary/$FILE
	else
		adb pull system/$FILE ../../../vendor/$VENDOR/$DEVICE/proprietary/$FILE
	fi
#	chmod 0755 ../../../vendor/$VENDOR/$DEVICE/proprietary/$FILE
done
#if [ "$ZIP" ]; then rm -rf tmp ; fi

(cat << EOF) | sed s/__DEVICE__/$DEVICE/g > ../../../vendor/samsung/$DEVICE/$DEVICE-vendor-blobs.mk
# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/__DEVICE__/extract-files.sh

PRODUCT_COPY_FILES += \\
    vendor/samsung/__DEVICE__/proprietary/bin/mrvlhcitool:system/bin/mrvlhcitool \\
    vendor/samsung/__DEVICE__/proprietary/bin/memsicd:system/bin/memsicd \\ 
    vendor/samsung/__DEVICE__/proprietary/bin/wifidir_init.conf:system/bin/wifidir_init.conf \\
    vendor/samsung/__DEVICE__/proprietary/bin/MarvellWirelessDaemon:system/bin/MarvellWirelessDaemon \\
    vendor/samsung/__DEVICE__/proprietary/bin/mwu:system/bin/mwu \\
    vendor/samsung/__DEVICE__/proprietary/bin/rfkill:system/bin/rfkill \\
    vendor/samsung/__DEVICE__/proprietary/bin/npsmobex:system/bin/npsmobex \\
    vendor/samsung/__DEVICE__/proprietary/bin/wlandutservice:system/bin/wlandutservice \\
    vendor/samsung/__DEVICE__/proprietary/bin/mcfg:system/bin/mcfg \\
    vendor/samsung/__DEVICE__/proprietary/bin/mfgloader:system/bin/mfgloader \\
    vendor/samsung/__DEVICE__/proprietary/bin/samsung_debug:system/bin/samsung_debug \\
    vendor/samsung/__DEVICE__/proprietary/bin/mwu_cli:system/bin/mwu_cli \\
    vendor/samsung/__DEVICE__/proprietary/bin/mpdc:system/bin/mpdc \\
    vendor/samsung/__DEVICE__/proprietary/bin/mpdc_d:system/bin/mpdc_d \\
    vendor/samsung/__DEVICE__/proprietary/bin/mpdc_svr:system/bin/mpdc_svr \\

PRODUCT_COPY_FILES += \\
    vendor/samsung/__DEVICE__/proprietary/lib/lib_gsd4t.so:system/lib/lib_gsd4t.so
    vendor/samsung/__DEVICE__/proprietary/lib/lib_gsd4t.so:system/lib/lib_gsd4t_factory.so

#    vendor/samsung/__DEVICE__/proprietary/lib/libbmm.so:system/lib/libbmm.so \\
#    vendor/samsung/__DEVICE__/proprietary/lib/libphycontmem.so:system/lib/libphycontmem.so \\
#    vendor/samsung/__DEVICE__/proprietary/lib/libpmemhelper.so:system/lib/libpmemhelper.so

#PRODUCT_COPY_FILES += \\
#    vendor/samsung/__DEVICE__/proprietary/lib/libopencore_author.so:system/lib/libopencore_author.so \\
#    vendor/samsung/__DEVICE__/proprietary/lib/libopencore_common.so:system/lib/libopencore_common.so \\
#    vendor/samsung/__DEVICE__/proprietary/lib/libopencore_download.so:system/lib/libopencore_download.so \\
#    vendor/samsung/__DEVICE__/proprietary/lib/libopencore_downloadreg.so:system/lib/libopencore_downloadreg.so \\
#    vendor/samsung/__DEVICE__/proprietary/lib/libopencore_mp4local.so:system/lib/libopencore_mp4local.so \\
#    vendor/samsung/__DEVICE__/proprietary/lib/libopencore_mp4localreg.so:system/lib/libopencore_mp4localreg.so \\
#    vendor/samsung/__DEVICE__/proprietary/lib/libopencore_net_support.so:system/lib/libopencore_net_support.so \\
#    vendor/samsung/__DEVICE__/proprietary/lib/libopencore_player.so:system/lib/libopencore_player.so \\
#    vendor/samsung/__DEVICE__/proprietary/lib/libopencore_rtsp.so:system/lib/libopencore_rtsp.so \\
#    vendor/samsung/__DEVICE__/proprietary/lib/libopencore_rtspreg.so:system/lib/libopencore_rtspreg.so \\
#    vendor/samsung/__DEVICE__/proprietary/lib/libopencorehw.so:system/lib/libopencorehw.so \\
#    vendor/samsung/__DEVICE__/proprietary/lib/libstagefright_color_conversion.so:system/lib/libstagefright_color_conversion.so \\
#    vendor/samsung/__DEVICE__/proprietary/lib/libstagefright_hardware_renderer.so:system/lib/libstagefright_hardware_renderer.so \\
#    vendor/samsung/__DEVICE__/proprietary/lib/libstagefrighthw.so:system/lib/libstagefrighthw.so
#    vendor/samsung/__DEVICE__/proprietary/lib/libomx_aacdec_sharedlibrary.so:system/lib/libomx_aacdec_sharedlibrary.so \\
#    vendor/samsung/__DEVICE__/proprietary/lib/libomx_amrdec_sharedlibrary.so:system/lib/libomx_amrdec_sharedlibrary.so \\
#    vendor/samsung/__DEVICE__/proprietary/lib/libomx_amrenc_sharedlibrary.so:system/lib/libomx_amrenc_sharedlibrary.so \\
#    vendor/samsung/__DEVICE__/proprietary/lib/libomx_avcdec_sharedlibrary.so:system/lib/libomx_avcdec_sharedlibrary.so \\
#    vendor/samsung/__DEVICE__/proprietary/lib/libomx_m4vdec_sharedlibrary.so:system/lib/libomx_m4vdec_sharedlibrary.so \\
#    vendor/samsung/__DEVICE__/proprietary/lib/libomx_mp3dec_sharedlibrary.so:system/lib/libomx_mp3dec_sharedlibrary.so \\
#    vendor/samsung/__DEVICE__/proprietary/lib/libomx_mrvl_sharedlibrary.so:system/lib/libomx_mrvl_sharedlibrary.so \\

PRODUCT_COPY_FILES += \\
    vendor/samsung/__DEVICE__/proprietary/etc/vold.fstab:system/etc/vold.fstab \\
    vendor/samsung/__DEVICE__/proprietary/etc/gps.conf:system/etc/gps.conf

#    vendor/samsung/__DEVICE__/proprietary/marvell/etc/asound.conf:system/etc/asound.conf \\
#    vendor/samsung/__DEVICE__/proprietary/etc/mrvl.cfg:system/etc/mrvl.cfg \\

#
# RIL
#
PRODUCT_COPY_FILES += \\
    vendor/samsung/__DEVICE__/proprietary/lib/libmarvell-ril.so:system/lib/libmarvell-ril.so \\
    vendor/samsung/__DEVICE__/proprietary/lib/libsecutil.so:system/lib/libsecutil.so \\
    vendor/samsung/__DEVICE__/proprietary/lib/libriloemhook.so:system/lib/libriloemhook.so \\
    vendor/samsung/__DEVICE__/proprietary/lib/libsvcmd.so:system/lib/libsvcmd.so

#
# Wireless
#
PRODUCT_COPY_FILES += \\
    vendor/samsung/__DEVICE__/proprietary/etc/wifidirect_defaults.conf:system/etc/wifidirect_defaults.conf \\
    vendor/samsung/__DEVICE__/proprietary/etc/firmware/mrvl/sd8787_uapsta.bin:system/etc/firmware/mrvl/sd8787_uapsta.bin \\
    vendor/samsung/__DEVICE__/proprietary/etc/firmware/mrvl/w8787_wlan_SDIO_bt_SDIO.bin:system/etc/firmware/mrvl/w8787_wlan_SDIO_bt_SDIO.bin \\
    vendor/samsung/__DEVICE__/proprietary/etc/firmware/mrvl/WlanCalData_ext.conf:system/etc/firmware/mrvl/WlanCalData_ext.conf \\
    vendor/samsung/__DEVICE__/proprietary/lib/libmrvldut.so:system/lib/libmrvldut.so \\
    vendor/samsung/__DEVICE__/proprietary/lib/libMarvellWireless.so:system/lib/libMarvellWireless.so


#
# Display (3D)
#
#PRODUCT_COPY_FILES += \\
#    vendor/samsung/__DEVICE__/proprietary/lib/egl/libEGL_MRVL.so:system/lib/egl/libEGL_MRVL.so \\
#    vendor/samsung/__DEVICE__/proprietary/lib/egl/libGLESv1_CM_MRVL.so:system/lib/egl/libGLESv1_CM_MRVL.so \\
#    vendor/samsung/__DEVICE__/proprietary/lib/egl/libGLESv2_MRVL.so:system/lib/egl/libGLESv2_MRVL.so

#
# Sensors, Lights etc
#
PRODUCT_COPY_FILES += \\
    vendor/samsung/__DEVICE__/proprietary/lib/hw/sensors.default.so:system/lib/hw/sensors.default.so \\
    vendor/samsung/__DEVICE__/proprietary/lib/hw/lights.default.so:system/lib/hw/lights.default.so \\
    vendor/samsung/__DEVICE__/proprietary/lib/hw/gps.default.so:system/lib/hw/gps.default.so

#
# Camera
#
PRODUCT_COPY_FILES += \\
    vendor/samsung/__DEVICE__/proprietary/lib/libcamera.so:system/lib/libcamera.so \\
    vendor/samsung/__DEVICE__/proprietary/cameradata/datapattern_420sp.yuv:system/cameradata/datapattern_420sp.yuv \\
    vendor/samsung/__DEVICE__/proprietary/cameradata/datapattern_front_420sp.yuv:system/cameradata/datapattern_front_420sp.yuv \\
    vendor/samsung/__DEVICE__/proprietary/cameradata/datapattern_420sp_alkon.yuv:system/cameradata/datapattern_420sp_alkon.yuv

#
# Files for battery charging screen
#
PRODUCT_COPY_FILES += \\
    vendor/samsung/__DEVICE__/proprietary/bin/playlpm:system/bin/playlpm \\
    vendor/samsung/__DEVICE__/proprietary/bin/charging_mode:system/bin/charging_mode \\
    vendor/samsung/__DEVICE__/proprietary/lib/libQmageDecoder.so:system/lib/libQmageDecoder.so \\
    vendor/samsung/__DEVICE__/proprietary/media/battery_charging_5.qmg:system/media/battery_charging_5.qmg \\
    vendor/samsung/__DEVICE__/proprietary/media/battery_charging_10.qmg:system/media/battery_charging_10.qmg \\
    vendor/samsung/__DEVICE__/proprietary/media/battery_charging_15.qmg:system/media/battery_charging_15.qmg \\
    vendor/samsung/__DEVICE__/proprietary/media/battery_charging_20.qmg:system/media/battery_charging_20.qmg \\
    vendor/samsung/__DEVICE__/proprietary/media/battery_charging_25.qmg:system/media/battery_charging_25.qmg \\
    vendor/samsung/__DEVICE__/proprietary/media/battery_charging_30.qmg:system/media/battery_charging_30.qmg \\
    vendor/samsung/__DEVICE__/proprietary/media/battery_charging_35.qmg:system/media/battery_charging_35.qmg \\
    vendor/samsung/__DEVICE__/proprietary/media/battery_charging_40.qmg:system/media/battery_charging_40.qmg \\
    vendor/samsung/__DEVICE__/proprietary/media/battery_charging_45.qmg:system/media/battery_charging_45.qmg \\
    vendor/samsung/__DEVICE__/proprietary/media/battery_charging_50.qmg:system/media/battery_charging_50.qmg \\
    vendor/samsung/__DEVICE__/proprietary/media/battery_charging_55.qmg:system/media/battery_charging_55.qmg \\
    vendor/samsung/__DEVICE__/proprietary/media/battery_charging_60.qmg:system/media/battery_charging_60.qmg \\
    vendor/samsung/__DEVICE__/proprietary/media/battery_charging_65.qmg:system/media/battery_charging_65.qmg \\
    vendor/samsung/__DEVICE__/proprietary/media/battery_charging_70.qmg:system/media/battery_charging_70.qmg \\
    vendor/samsung/__DEVICE__/proprietary/media/battery_charging_75.qmg:system/media/battery_charging_75.qmg \\
    vendor/samsung/__DEVICE__/proprietary/media/battery_charging_80.qmg:system/media/battery_charging_80.qmg \\
    vendor/samsung/__DEVICE__/proprietary/media/battery_charging_85.qmg:system/media/battery_charging_85.qmg \\
    vendor/samsung/__DEVICE__/proprietary/media/battery_charging_90.qmg:system/media/battery_charging_90.qmg \\
    vendor/samsung/__DEVICE__/proprietary/media/battery_charging_95.qmg:system/media/battery_charging_95.qmg \\
    vendor/samsung/__DEVICE__/proprietary/media/battery_charging_100.qmg:system/media/battery_charging_100.qmg \\
    vendor/samsung/__DEVICE__/proprietary/media/chargingwarning.qmg:system/media/chargingwarning.qmg \\
    vendor/samsung/__DEVICE__/proprietary/media/Disconnected.qmg:system/media/Disconnected.qmg

EOF

./setup-makefiles.sh
