#!/bin/sh

# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

VENDOR=samsung
DEVICE=xcover

rm -rf ../../../vendor/$VENDOR/$DEVICE/*
mkdir -p ../../../vendor/$VENDOR/$DEVICE/proprietary

ZIP="true"

#if [ -f "$1" ]; then
#	rm -rf tmp
#	mkdir tmp
#	unzip -q "$1" -d tmp
#	if [ $? != 0 ]; then
#		echo "$1 is not a valid zip file. Bye."
#		exit 1
#	fi
#	ZIP="true"
#	echo "$1 successfully unzip'd. Copying files..."
#else
#	unset ZIP
#fi

DIRS="
bin
cameradata
etc
etc/firmware
etc/firmware/mrvl
lib
lib/egl
lib/hw
media
"

for DIR in $DIRS; do
	mkdir -p ../../../vendor/$VENDOR/$DEVICE/proprietary/$DIR
	chmod 0755 ../../../vendor/$VENDOR/$DEVICE/proprietary/$DIR
done

FILES="
etc/vold.fstab
etc/gps.conf
lib/lib_gsd4t.so
lib/liblabtool.so
lib/libmarvell-ril.so
lib/libquramimagecodec.so
lib/libQmageDecoder.so
lib/hw/sensors.default.so
lib/hw/gps.default.so
lib/hw/lights.default.so
bin/mtilatcmd
bin/ml_setid
bin/validationif
bin/mtsd
bin/audioserver
bin/eeh
bin/hwacc
bin/memsicd
bin/playlpm
bin/charging_mode
media/battery_charging_5.qmg
media/battery_charging_10.qmg
media/battery_charging_15.qmg
media/battery_charging_20.qmg
media/battery_charging_25.qmg
media/battery_charging_30.qmg
media/battery_charging_35.qmg
media/battery_charging_40.qmg
media/battery_charging_45.qmg
media/battery_charging_50.qmg
media/battery_charging_55.qmg
media/battery_charging_60.qmg
media/battery_charging_65.qmg
media/battery_charging_70.qmg
media/battery_charging_75.qmg
media/battery_charging_80.qmg
media/battery_charging_85.qmg
media/battery_charging_90.qmg
media/battery_charging_95.qmg
media/battery_charging_100.qmg
media/chargingwarning.qmg
media/Disconnected.qmg
media/TemperatureError.qmg
"

#lib/libsecutil.so
#lib/libriloemhook.so
#lib/libsvcmd.so
#lib/libasound.so
#lib/lib_gsd4t_factory.so
#lib/libpmemhelper.so
#lib/libphycontmem.so
#lib/lib_gsd4t_factory.so
#lib/libseccameraadaptor.so
#lib/libseccamera.so
#etc/mrvl.cfg
#bin/displaymodel
#etc/dms.cfg
#etc/firmware/mrvl/WlanCalData_ext.conf
#etc/firmware/mrvl/w8787_wlan_SDIO_bt_SDIO.bin
#etc/firmware/mrvl/sd8787_uapsta.bin
#etc/wifidirect_defaults.conf
#cameradata/datapattern_420sp.yuv
#cameradata/datapattern_front_420sp.yuv
#cameradata/datapattern_420sp_alkon.yuv
#lib/hw/audio.primary.default.so
#lib/hw/audio.a2dp.default.so
#lib/hw/audio_policy.default.so
#lib/libbmm.so
#lib/libcamera.so
#lib/libGAL.so
#lib/libgcu.so
#lib/egl/libEGL_MRVL.so
#lib/egl/libGLESv1_CM_MRVL.so
#lib/egl/libGLESv2_MRVL.so
#lib/hw/hwcomposer.default.so
#lib/hw/gralloc.default.so
#lib/libopencore_author.so
#lib/libopencore_common.so
#lib/libopencore_download.so
#lib/libopencore_downloadreg.so
#lib/libopencore_mp4local.so
#lib/libopencore_mp4localreg.so
#lib/libopencore_net_support.so
#lib/libopencore_player.so
#lib/libopencore_rtsp.so
#lib/libopencore_rtspreg.so
#lib/libopencorehw.so

(cat << EOF) | sed s/__DEVICE__/$DEVICE/g > ../../../vendor/samsung/$DEVICE/$DEVICE-vendor-blobs.mk
#
# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/__DEVICE__/extract-makefiles.sh
#

EOF

echo "PRODUCT_COPY_FILES += \\" >> ../../../vendor/samsung/xcover/xcover-vendor-blobs.mk
for FILE in $FILES; do
	echo $FILE
	if [ "$ZIP" ]; then
		cp system/"$FILE" ../../../vendor/$VENDOR/$DEVICE/proprietary/$FILE
	else
		adb pull system/$FILE ../../../vendor/$VENDOR/$DEVICE/proprietary/$FILE
	fi
	echo "    vendor/samsung/xcover/proprietary/$FILE:system/$FILE \\" >> ../../../vendor/samsung/xcover/xcover-vendor-blobs.mk 
done

chmod -v 0755 ../../../vendor/$VENDOR/$DEVICE/proprietary/bin/*
chmod -v 0664 ../../../vendor/$VENDOR/$DEVICE/proprietary/lib/*.so
chmod -v 0664 ../../../vendor/$VENDOR/$DEVICE/proprietary/lib/*/*.so

#if [ "$ZIP" ]; then rm -rf tmp ; fi

(cat << EOF) | sed s/__DEVICE__/$DEVICE/g > ../../../vendor/samsung/$DEVICE/$DEVICE-vendor.mk
#
# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/__DEVICE__/extract-makefiles.sh

# Pick up overlay for features that depend on non-open-source files
DEVICE_PACKAGE_OVERLAYS := vendor/samsung/__DEVICE__/overlay

\$(call inherit-product, vendor/samsung/__DEVICE__/__DEVICE__-vendor-blobs.mk)
EOF
