sudo adb pull /system/etc/permissions/hw-features.xml
sudo adb pull /system/etc/permissions/platform.xml
sudo adb pull /system/etc/permissions/com.samsung.android.sec_platform_library.xml
sudo adb pull /system/etc/permissions/android.hardware.camera.flash-autofocus.xml
sudo adb pull /system/etc/permissions/android.software.live_wallpaper.xml
sudo adb pull /system/etc/permissions/android.hardware.sensor.proximity.xml
sudo adb pull /system/etc/permissions/com.sec.android.keystring.xml
sudo adb pull /system/etc/permissions/android.hardware.telephony.gsm.xml
sudo adb pull /system/etc/permissions/seccamera.xml
sudo adb pull /system/etc/permissions/com.sec.android.riloemhook.xml
sudo adb pull /system/etc/permissions/android.hardware.touchscreen.multitouch.distinct.xml
sudo adb pull /system/etc/permissions/sec_feature.xml
sudo adb pull /system/etc/permissions/sw-features.xml
sudo adb pull /system/etc/permissions/android.hardware.location.gps.xml
sudo adb pull /system/etc/permissions/com.samsung.device.xml
sudo adb pull /system/etc/permissions/android.hardware.camera.autofocus.xml
sudo adb pull /system/etc/permissions/com.google.android.maps.xml
sudo adb pull /system/etc/permissions/android.hardware.touchscreen.multitouch.xml
sudo adb pull /system/etc/permissions/android.hardware.wifi.xml
sudo adb pull /system/etc/permissions/com.android.location.provider.xml
sudo adb pull /system/etc/permissions/handheld_core_hardware.xml
sudo adb pull /system/etc/permissions/com.marvell.android.mtil_library.xml
sudo adb pull /system/etc/permissions/touchwiz.xml

